package com.queyue.util.dbf.general;

public class T_TDD {

	public String ksh;
	public String zkzh;
	public String xm;
	public String xbdm;
	public String csny;
	public String zzmmdm;
	public String mzdm;
	public String kslbdm;
	public String bylbdm;
	public String zxdm;
	public String zxmc;
	public String wyyzdm;
	public String hkdj;
	public String bmdw;
	public String kstz;
	public String xtdw;
	public String dqdm;
	public String sfzh;
	public String jtdz;
	public String yzbm;
	public String lxdh;
	public String hkkh;
	public String kstc;
	public String ksjlhcf;
	public String wyks;
	public String zsyj;
	public String kslxdm;
	public String sjr;
	public String ysjzdm;
	public String wytl;
	public String pcdm;
	public String kldm;
	public String tddw;
	public String jhxz;
	public String cj;
	public String tzcj;
	public String tdcj;
	public String zgf;
	public String yxdrcj;
	public String zyytjzcj;
	public String zyytfjcj;
	public String tdzy;
	public String dqtddw;
	public String ytzy;
	public String lqzy;
	public String tdyydm;
	public String bz;
	public String zyhg;
	public String tjhg;
	public String lqfs;
	public String kszt;
	public String sdbz;
	public String tddwdm1;
	public String zydh1;
	public String tddwdm2;
	public String zydh2;
	public String tddwdm3;
	public String zydh3;
	public String tddwdm4;
	public String zydh4;
	public String tddwdm5;
	public String zydh5;
	public String tddwdm6;
	public String zydh6;
	public String zytz;
	public String zyzytj;
	public String dxtj;
	public String zytjfc;
	public String zysxdm1;
	public String zysxdm2;
	public String zysxdm3;
	public String zysxdm4;
	public String zysxdm5;
	public String zysxdm6;
	public String tjjldm;
	public String bh;
	public String kslsczbz;
	public String task_tag;
//	public String gkcjx01;
//	public String gkcjx02;
//	public String gkcjx03;
//	public String gkcjx04;
//	public String gkcjx12;
//	public String gkcjx14;
//	public String gkcjx15;
//	public String gkcjx16;
//	public String gkcjx21;
//	public String gkcjx22;
//	public String gkcjx31;
//	public String gkcjx90;
//	public String gkcjx91;
//	public String gkcjx92;
//	public String gkcjx93;
//	public String gkcjx94;
//	public String gkcjx95;
//	public String gkcjx96;
//	public String gkcjx97;
//	public String gkcjx98;
//	public String gkcjx99;
}
